import { expect, test } from '@playwright/test'
import { go, startDemo } from './helpers'

test('categorías v2: crear con icono y color, renombrar una de Clara, archivar con reasignación, reordenar y grupos', async ({ page }) => {
  await startDemo(page)
  await go(page, '/ajustes/categorias')
  await expect(page.getByRole('heading', { name: 'Categorías' })).toBeVisible()

  // Crear una propia con color e icono.
  await page.getByRole('button', { name: 'Nueva categoría' }).click()
  const dialog = page.getByRole('dialog', { name: 'Nueva categoría' })
  await dialog.getByLabel('Nombre').fill('Gimnasio')
  await dialog.getByRole('button', { name: 'Lima' }).click()
  await dialog.getByRole('button', { name: 'heart', exact: true }).click()
  await dialog.getByLabel('Grupo').selectOption({ label: 'Estilo de vida' })
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Categoría guardada')).toBeVisible()
  const gym = page.getByTestId(/^category-c_/).filter({ hasText: 'Gimnasio' })
  await expect(gym).toBeVisible()
  await expect(gym.getByText('Propia')).toBeVisible()

  // Renombrar una de Clara (preferencia) y que se vea en el formulario de movimiento.
  await page.getByRole('button', { name: 'Editar: Restaurantes y café' }).click()
  const edit = page.getByRole('dialog', { name: 'Editar categoría' })
  await edit.getByLabel('Nombre').fill('Comer fuera')
  await edit.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByTestId('category-dining')).toContainText('Comer fuera')
  await go(page, '/movimientos/nuevo')
  await expect(page.getByLabel('Categoría', { exact: true }).locator('option', { hasText: 'Comer fuera' })).toHaveCount(1)
  await expect(page.getByLabel('Categoría', { exact: true }).locator('option', { hasText: 'Restaurantes y café' })).toHaveCount(0)

  // Archivar una de Clara con reasignación: sus registros pasan a otra categoría; nada se borra.
  await go(page, '/movimientos')
  const before = await page.locator('.item').count()
  await go(page, '/ajustes/categorias')
  const supermarket = page.getByTestId('category-groceries')
  const usesText = await supermarket.locator('.badge').last().textContent()
  const uses = Number(/\d+/.exec(usesText ?? '0')?.[0] ?? 0)
  expect(uses).toBeGreaterThan(0)
  await page.getByRole('button', { name: /^Archivar.*Supermercado$/ }).click()
  const arch = page.getByRole('dialog', { name: '¿Archivar «Supermercado»?' })
  await arch.getByLabel('Mover sus registros a').selectOption({ label: 'Comer fuera' })
  await arch.getByRole('button', { name: 'Archivar', exact: true }).click()
  await expect(page.getByText(/Categoría archivada; \d+ registros? movidos?/)).toBeVisible()
  await expect(page.getByTestId('category-groceries')).toHaveCount(0)
  await page.getByRole('switch', { name: 'Mostrar archivadas' }).click()
  await expect(page.getByTestId('category-groceries')).toContainText('Archivada')
  await expect(page.getByTestId('category-groceries')).toContainText('0 usos')
  await go(page, '/movimientos')
  expect(await page.locator('.item').count()).toBe(before)
  await expect(page.getByLabel('Categoría', { exact: true }).locator('option', { hasText: 'Supermercado' })).toHaveCount(1) // el filtro incluye archivadas

  // Restaurar y reordenar.
  await go(page, '/ajustes/categorias')
  await page.getByRole('switch', { name: 'Mostrar archivadas' }).click()
  await page.getByRole('button', { name: /^Reactivar.*Supermercado$/ }).click()
  await expect(page.getByText('Categoría reactivada')).toBeVisible()
  const firstBefore = await page.getByTestId(/^category-/).first().getAttribute('data-testid')
  await page.getByRole('button', { name: /^Bajar/ }).first().click()
  await expect(page.getByTestId(/^category-/).first()).not.toHaveAttribute('data-testid', firstBefore!)

  // Grupo propio: crear, mover una categoría y eliminar el grupo (la categoría vuelve a «Otros»).
  await page.getByRole('button', { name: 'Nuevo grupo' }).click()
  const g = page.getByRole('dialog', { name: 'Nuevo grupo' })
  await g.getByLabel('Nombre').fill('Peques')
  await g.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Grupo guardado')).toBeVisible()
  await page.getByRole('button', { name: 'Editar: Hijos' }).click()
  await page.getByRole('dialog', { name: 'Editar categoría' }).getByLabel('Grupo').selectOption({ label: 'Peques' })
  await page.getByRole('dialog', { name: 'Editar categoría' }).getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Peques' })).toContainText('Hijos')
  await page.getByRole('button', { name: 'Eliminar grupo: Peques' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Eliminar grupo' }).click()
  await expect(page.getByText('Grupo eliminado')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Otros' })).toContainText('Hijos')
})

test('onboarding: elegir categorías y periodo; las no marcadas no aparecen en el formulario', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-28T12:00:00-04:00') })
  await page.goto('/')
  await page.getByRole('button', { name: 'Configurar con mis datos' }).click()
  await expect(page.getByRole('heading', { name: 'Tus categorías' })).toBeVisible()
  await expect(page.getByText('16 seleccionadas')).toBeVisible()
  await page.getByLabel('Mascotas').uncheck()
  await expect(page.getByText('15 seleccionadas')).toBeVisible()
  await page.getByLabel('Nombre de la categoría').fill('Bicicleta')
  await page.getByRole('button', { name: 'Crear una propia' }).click()
  await expect(page.getByText('«Bicicleta» se creará al terminar la configuración.')).toBeVisible()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByLabel('Periodo del presupuesto')).toHaveValue('month')
  await page.getByLabel('Saldo disponible').fill('500')
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('radio', { name: 'No tengo fecha' }).check()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Ver mi resultado ahora' }).click()
  await page.getByRole('button', { name: 'Empezar a usar Clara' }).click()
  await expect(page.getByTestId('available')).toHaveText('$500.00')
  // Periodo mensual: etiqueta del mes, días restantes contando hoy (28-sep → 3) y safe to spend por día/semana/periodo.
  await expect(page.locator('.hero__sub')).toHaveText('septiembre de 2026 · quedan 3 días')
  const safe = page.getByTestId('safe-to-spend')
  await expect(safe.locator('.stat__value')).toHaveText('$166.66')
  await safe.getByRole('radio', { name: 'Periodo' }).check()
  await expect(safe.locator('.stat__value')).toHaveText('$500.00')
  await safe.getByRole('radio', { name: 'Semana' }).check()
  await expect(safe.locator('.stat__value')).toHaveText('$500.00')
  await go(page, '/movimientos/nuevo')
  const select = page.getByLabel('Categoría', { exact: true })
  await expect(select.locator('option', { hasText: 'Mascotas' })).toHaveCount(0)
  await expect(select.locator('option', { hasText: 'Bicicleta' })).toHaveCount(1)
  await expect(select.locator('option', { hasText: 'Teléfono e internet' })).toHaveCount(0)
})
