import { expect, test } from '@playwright/test'
import { applyFilters, openFilters, go, openApp, openDetails, startDemo } from './helpers'

test('etiquetas: crear en Ajustes, usar en el formulario, filtrar el historial y borrar con deshacer', async ({ page }) => {
  await startDemo(page)
  await go(page, '/ajustes?seccion=etiquetas')
  await page.getByRole('button', { name: 'Nueva etiqueta' }).click()
  const dialog = page.getByRole('dialog', { name: 'Nueva etiqueta' })
  await dialog.getByLabel('Nombre').fill('Viaje')
  await dialog.getByRole('button', { name: 'Celeste' }).click()
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Etiqueta guardada')).toBeVisible()
  await expect(page.getByTestId('tag-list')).toContainText('Viaje')

  await go(page, '/movimientos/nuevo')
  await page.getByLabel('Importe', { exact: true }).fill('12')
  await openDetails(page)
  await page.getByLabel('Comercio (opcional)').fill('Tienda del aeropuerto')
  await page.getByTestId('tag-chips').getByRole('button', { name: 'Viaje' }).click()
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Movimiento guardado').first()).toBeVisible()

  await go(page, '/movimientos')
  await (await openFilters(page)).getByRole('group', { name: 'Etiquetas' }).getByRole('button', { name: 'Viaje' }).click()
  await applyFilters(page)
  await expect(page.locator('.summary-line')).toContainText('1 movimiento')
  await go(page, '/ajustes?seccion=etiquetas')
  await expect(page.getByTestId('tag-list')).toContainText('1 movimiento')
  await page.getByRole('button', { name: /^Eliminar ?: Viaje$/ }).click()
  await expect(page.getByText('Etiqueta eliminada')).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer' }).click()
  await expect(page.getByTestId('tag-list')).toContainText('Viaje')
  await expect(page.getByTestId('tag-list')).toContainText('0 movimientos')
})

test('copias locales: hacer copia ahora, listar, restaurar con vista previa y deshacer; borrar todo exige escribir la palabra', async ({ page }) => {
  await startDemo(page)
  await go(page, '/ajustes?seccion=copias-locales')
  await expect(page.getByText('Todavía no hay copias locales.')).toBeVisible()
  await page.getByTestId('backup-now').click()
  await expect(page.getByText('Copia local guardada')).toBeVisible()
  await expect(page.getByTestId('local-backup-list').locator('li')).toHaveCount(1)
  await expect(page.getByTestId('local-backup-list')).toContainText('Manual')

  // Un cambio, luego restaurar la copia: el cambio desaparece y se puede deshacer.
  await go(page, '/movimientos/nuevo')
  await page.getByLabel('Importe', { exact: true }).fill('9')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('Movimiento guardado').first()).toBeVisible()
  await go(page, '/ajustes?seccion=copias-locales')
  await page.getByRole('button', { name: /^Restaurar ?: / }).click()
  const confirm = page.getByRole('dialog', { name: '¿Restaurar esta copia?' })
  await expect(confirm).toContainText('Moneda: CAD')
  await confirm.getByRole('button', { name: 'Restaurar' }).click()
  await expect(page.getByText('Copia restaurada')).toBeVisible()
  // Antes de restaurar se guardó otra copia.
  await expect(page.getByTestId('local-backup-list')).toContainText('Antes de restaurar')
  await page.getByRole('button', { name: 'Deshacer' }).click()

  // Zona de peligro: el botón solo se activa con la casilla y la palabra.
  await go(page, '/ajustes?seccion=reinicio')
  await page.getByRole('button', { name: 'Borrar todos los datos' }).click()
  const danger = page.getByRole('dialog', { name: '¿Borrar todos los datos?' })
  const confirmBtn = danger.getByRole('button', { name: 'Borrar todo' })
  await expect(confirmBtn).toBeDisabled()
  await danger.getByRole('checkbox').check()
  await expect(confirmBtn).toBeDisabled()
  await danger.getByLabel('Escribe BORRAR para confirmar').fill('borrar')
  await expect(confirmBtn).toBeEnabled()
  await danger.getByRole('button', { name: 'Cancelar' }).click()
})

test('bloqueo con PIN: se pide al recargar, rechaza el PIN incorrecto, desbloquea y se puede quitar', async ({ page }) => {
  await startDemo(page)
  await go(page, '/ajustes?seccion=bloqueo')
  await page.getByRole('switch', { name: 'Pedir PIN al abrir' }).click()
  const dialog = page.getByRole('dialog', { name: 'Elige un PIN' })
  await dialog.getByLabel('PIN', { exact: true }).fill('2468')
  await dialog.getByLabel('Repite el PIN').fill('2460')
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(dialog.getByText('Los dos PIN no coinciden.')).toBeVisible()
  await dialog.getByLabel('Repite el PIN').fill('2468')
  await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByText('PIN guardado; se pedirá al abrir')).toBeVisible()

  await page.reload()
  await expect(page.getByTestId('lock-screen')).toBeVisible()
  await expect(page.getByTestId('available')).toHaveCount(0)
  await page.getByLabel('PIN').fill('1111')
  await page.getByRole('button', { name: 'Desbloquear' }).click()
  await expect(page.getByText('PIN incorrecto.')).toBeVisible()
  await page.getByLabel('PIN').fill('2468')
  await page.getByRole('button', { name: 'Desbloquear' }).click()
  await expect(page.getByTestId('lock-screen')).toHaveCount(0)
  await go(page, '/')
  await expect(page.getByTestId('available')).toBeVisible()

  await go(page, '/ajustes?seccion=bloqueo')
  await page.getByRole('switch', { name: 'Pedir PIN al abrir' }).click()
  await expect(page.getByText('Bloqueo quitado')).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('lock-screen')).toHaveCount(0)
  await go(page, '/')
  await expect(page.getByTestId('available')).toBeVisible()
})

test('apariencia y exportación: idioma con bandera, moneda bloqueada con registros y libre sin ellos, CSV de categorías, legal', async ({ page }) => {
  await startDemo(page)
  await go(page, '/ajustes/formato')
  await expect(page.getByTestId('language-chips').getByRole('button', { name: /Español/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('current-period')).toHaveCount(0) // la demo usa «hasta mi próximo ingreso»
  await page.getByTestId('change-currency').click()
  await page.getByLabel('Buscar moneda').fill('mex')
  await page.getByRole('dialog').getByRole('button', { name: /MXN/ }).click()
  await expect(page.getByText('Ya hay importes guardados')).toBeVisible()

  await go(page, '/ajustes/exportar')
  const download = page.waitForEvent('download')
  await page.getByLabel('Qué exportar').selectOption('categories')
  await page.getByTestId('export-csv').click()
  const file = await download
  expect(file.suggestedFilename()).toMatch(/^clara-categories-\d{4}-\d{2}-\d{2}\.csv$/)
  await expect(page.getByText('Archivo CSV generado')).toBeVisible()

  await go(page, '/legal/privacidad')
  await expect(page.getByRole('heading', { name: 'Privacidad' })).toBeVisible()
  await expect(page.getByText('Dónde están tus datos')).toBeVisible()
})

test('moneda: un presupuesto nuevo sin importes (saldo en cero) puede cambiarla desde el selector con búsqueda', async ({ page }) => {
  await openApp(page)
  await page.getByRole('button', { name: 'Configurar con mis datos' }).click()
  await page.getByRole('button', { name: 'Continuar' }).click()
  // QA-01: un saldo de referencia distinto de cero ya es un importe guardado y bloquea el cambio (audit-regressions.spec).
  await page.getByLabel('Saldo disponible').fill('0')
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('radio', { name: 'No tengo fecha' }).check()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Ver mi resultado ahora' }).click()
  await page.getByRole('button', { name: 'Empezar a usar Clara' }).click()
  await expect(page.getByTestId('available')).toBeVisible()
  await go(page, '/ajustes/formato')
  await page.getByTestId('change-currency').click()
  await page.getByRole('dialog').getByRole('button', { name: /MXN/ }).click()
  await expect(page.getByText('Moneda cambiada a MXN')).toBeVisible()
})
